config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static/home'

  root :to => "static#home"
  resources :comments
  resources :events
  resources :joins
  resources :pins
  resources :places
  resources :user_profs
  get 'check_user_prof', to: 'user_profs#check'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :user_prof
  # belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  # belongs_to :pin
  # belongs_to :join
  # belongs_to :event_lang_link
  # belongs_to :place
  # has_many :comments
end

app/models/event_lang_link.rb
class EventLangLink < ApplicationRecord
  # has_many :lang_tags
  # has_many :events
end

app/models/join.rb
class Join < ApplicationRecord
  # has_many :user_profs
  # has_many :events
end

app/models/lang_tag.rb
class LangTag < ApplicationRecord
  # belongs_to :user_pfof_lang_link
  # belongs_to :event_lang_link
end

app/models/pin.rb
class Pin < ApplicationRecord
  # has_many :user_profs
  # has_many :events
end

app/models/place.rb
class Place < ApplicationRecord
  # belongs_to :event
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_prof
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_pfof_lang_link.rb
class UserPfofLangLink < ApplicationRecord
  # has_many :user_profs
  # has_many :lang_tags
end

app/models/user_prof.rb
class UserProf < ApplicationRecord
  belongs_to :user
  belongs_to :pin
  belongs_to :join
  belongs_to :user_pfof_lang_link
  has_many :comments
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_profs_helper.rb
module UserProfsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bungee+Hairline" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Black+Ops+One" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav>

        <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
        <% if user_signed_in? %>

          <!-- リンク先をcurrent_user.idに統一するために定義 -->
          <% id = current_user.id %>

          <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
          <!-- *_path はUserモデルを作成したときに、
            deviseにより自動で作成されてますので、rake routesで確認できます -->
          Logged in as <strong><%= current_user.email %></strong>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          <%= link_to "user一覧", user_profs_path %>
          <%= link_to "プロフィール変更", edit_user_prof_path(id) %>
          <%= link_to "イベント", events_path %>
          <%= link_to "カフェ一覧", places_path %>
        <% else %>
          <%= link_to "サインイン", new_user_registration_path %>
          <%= link_to "ログイン", new_user_session_path %>
        <% end %>
      </nav>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/bxslider/4.2.5/jquery.bxslider.js' %>
  </body>
</html>